nohup 1

diff --git a/3dpssh b/3dpssh
--- a/3dpssh
+++ b/3dpssh
@@ -30,7 +30,7 @@ LOCAL_SSH_PID=''
 function EXIT_trap ()
 {
     if [[ ! -z "${LOCAL_SSH_PID}" ]] ; then
-	kill ${LOCAL_SSH_PID}
+        kill ${LOCAL_SSH_PID}
     fi
 }
 trap 'EXIT_trap' EXIT
@@ -53,8 +53,8 @@ if [[ ! -d ${HOME}/${_3dpssh_dir} ]] ; then
     echo -n "It appears that 3dpssh is not configured.  Would you like to configure it now? "
     read answer
     if [[ "${answer}" != 'y' ]] ; then
-	echo "Not configuring..."
-	exit
+        echo "Not configuring..."
+        exit
     fi
 
     echo -n "3d party host: "
@@ -64,8 +64,8 @@ if [[ ! -d ${HOME}/${_3dpssh_dir} ]] ; then
 
     mkdir -p ${HOME}/${_3dpssh_dir}
     cat <<-EOF > ${HOME}/${_3dpssh_dir}/.config
-	_3dpssh_host="${_3dpssh_host}"
-	_3dpssh_local_name="${_3dpssh_local_name}"
+        _3dpssh_host="${_3dpssh_host}"
+        _3dpssh_local_name="${_3dpssh_local_name}"
 EOF
 fi
 
@@ -83,14 +83,14 @@ function get_remote_home_and_connection_list_helper ()
 
     # Create working directory (_3dpssh_dir) if necessary
     if [[ ! -d \${HOME}/${_3dpssh_dir} ]] ; then
-    	mkdir -p \${HOME}/${_3dpssh_dir}
+        mkdir -p \${HOME}/${_3dpssh_dir}
     fi
 
     # Prune dead connections
-    for i in \${HOME}/${_3dpssh_dir}/* ; do	    
-    	if ! grep -q \${i} /proc/net/unix ; then
-    	    rm -f \${i}
-    	fi
+    for i in \${HOME}/${_3dpssh_dir}/* ; do
+        if ! grep -q \${i} /proc/net/unix ; then
+            rm -f \${i}
+        fi
     done
 
     # Returns two things:
@@ -98,7 +98,7 @@ function get_remote_home_and_connection_list_helper ()
     #    a list of live connections.
     echo \${HOME}
     echo \${HOME}/${_3dpssh_dir}/*
-}    
+}
 "
 #declare -f check_3d_party_setup_helper
 
@@ -108,11 +108,11 @@ function get_remote_home_and_connection_list_helper ()
 function get_remote_home_and_connection_list ()
 {
     local list
-    
+
     list=$( \
-	    ssh ${_3dpssh_host} \
-		"$(declare -f get_remote_home_and_connection_list_helper) ; get_remote_home_and_connection_list_helper" \
-	)
+            ssh ${_3dpssh_host} \
+                "$(declare -f get_remote_home_and_connection_list_helper) ; get_remote_home_and_connection_list_helper" \
+        )
 
     REMOTE_HOME="$(echo "${list}" | head -n 1)"
     CONNECTION_LIST="$(echo "${list}" | tail -n 1)"
@@ -125,9 +125,9 @@ function check_if_connection_is_available ()
 
     found=1
     for i in ${CONNECTION_LIST} ; do
-	if [[ "$(basename "${i}")" == "${1}" ]] ; then
-	    found=0
-	fi
+        if [[ "$(basename "${i}")" == "${1}" ]] ; then
+            found=0
+        fi
     done
 
     return ${found}
@@ -137,20 +137,20 @@ function check_if_connection_is_available ()
 function check_3d_party_setup ()
 {
     get_remote_home_and_connection_list
-    
+
     if ! check_if_connection_is_available ${_3dpssh_local_name} ; then
-	echo "Backend connection not found, starting it..."
+        echo "Backend connection not found, starting it..."
 
-	pkill -f "ssh -fAXN -R " || :
-	ssh -fAXN -R ${REMOTE_HOME}/${_3dpssh_dir}/${_3dpssh_local_name}:127.0.0.1:22 ${_3dpssh_host}
+        pkill -f "ssh -fAXN -R " || :
+        ssh -fAXN -R ${REMOTE_HOME}/${_3dpssh_dir}/${_3dpssh_local_name}:127.0.0.1:22 ${_3dpssh_host}
 
-	get_remote_home_and_connection_list
-    
-	# if not found after re-start, somethings broken
-	if ! check_if_connection_is_available ${_3dpssh_local_name} ; then
-	    echo "Starting backend connection failed.  Sum Ting Wong"
-	    exit 1
-	fi
+        get_remote_home_and_connection_list
+
+        # if not found after re-start, somethings broken
+        if ! check_if_connection_is_available ${_3dpssh_local_name} ; then
+            echo "Starting backend connection failed.  Sum Ting Wong"
+            exit 1
+        fi
     fi
 }
 
@@ -163,13 +163,15 @@ function connection_setup ()
 
     # Search for an available port:
     while nc -z 127.0.0.1 ${LOCAL_PORT} ; do
-	LOCAL_PORT=$((LOCAL_PORT + 1))
+        LOCAL_PORT=$((LOCAL_PORT + 1))
     done
 
-    # --> race condition here on LOCAL_PORT <-- 
+    # --> race condition here on LOCAL_PORT <--
 
     # Setup forward link
+    echo 1
     ssh -AXN -L 127.0.0.1:${LOCAL_PORT}:${REMOTE_HOME}/${_3dpssh_dir}/${1} ${_3dpssh_host} &
+    echo 2
     # --> race condition here on LOCAL_SSH_PID <--
     LOCAL_SSH_PID=${!}
 
@@ -178,40 +180,40 @@ function connection_setup ()
     i=0
     echo -n "Connecting "
     while ! nc -z 127.0.0.1 ${LOCAL_PORT} ; do
-	case ${i} in
-	    ( 0 ) echo -ne '-\b' 
-	    ;;
-	    ( 1 ) echo -ne '\\\b' 
-	    ;;
-	    ( 2 ) echo -ne '|\b'
-	    ;;
-	    ( 3 ) echo -ne '/\b'
-	    ;;
-	    ( * ) echo 'sum ting wong'
-	    exit 1
-	    ;;
-	esac
+        case ${i} in
+            ( 0 ) echo -ne '-\b'
+            ;;
+            ( 1 ) echo -ne '\\\b'
+            ;;
+            ( 2 ) echo -ne '|\b'
+            ;;
+            ( 3 ) echo -ne '/\b'
+            ;;
+            ( * ) echo 'sum ting wong'
+            exit 1
+            ;;
+        esac
         i=$(( (i+1) % 4 ))
-	sleep 0.2
+        sleep 0.2
     done
     echo -en "\r"
 
     # Note: the "ssh -AXN -L ..." created in here will be terminated
     # in the EXIT_trap function.
     #
-    # Thus a 
+    # Thus a
     #     kill ${local_ssh_pid}
     # is not needed.
-}    
+}
 
 
 function list_available_connections ()
 {
     local i
-    
+
     echo -e "Available Connections:"
     for i in ${CONNECTION_LIST} ; do
-	echo -e "\t$(basename ${i})"
+        echo -e "\t$(basename ${i})"
     done
 }
 
@@ -219,39 +221,39 @@ function list_available_connections ()
 function do_ssh ()
 {
     connection_setup ${1}
-    
+
     ssh \
-	-o GlobalKnownHostsFile=/dev/null \
-	-o UserKnownHostsFile=/dev/null \
-	-o StrictHostKeyChecking=no \
-	-p ${LOCAL_PORT} \
-	127.0.0.1 \
-	|| :
+        -o GlobalKnownHostsFile=/dev/null \
+        -o UserKnownHostsFile=/dev/null \
+        -o StrictHostKeyChecking=no \
+        -p ${LOCAL_PORT} \
+        127.0.0.1 \
+        || :
 }
 
 
 function do_connection_environment ()
 {
     connection_setup ${1}
-    
+
     echo "For ssh/scp/rsync/sshfs, use \"localhost\" for ${1}."
     echo "You are now in a sub-shell ... ^D to exit"
-    
+
     export -n SHELLOPTS
     bash --rcfile <(echo \
-			". ~/.bashrc;" \
-			"PS1=\"[localhost-->${1}] \${PS1}\";" \
-			"alias rsync=\"rsync -e 'ssh -p ${LOCAL_PORT}'\";" \
-			"alias ssh=\"ssh" \
-			"-o GlobalKnownHostsFile=/dev/null" \
-			"-o UserKnownHostsFile=/dev/null" \
-			"-o StrictHostKeyChecking=no" \
-			"-p ${LOCAL_PORT}\";" \
-			"alias sshfs=\"sshfs -p ${LOCAL_PORT}\";" \
-			"alias scp=\"scp -P ${LOCAL_PORT}\"" \
-		   ) || :
+                        ". ~/.bashrc;" \
+                        "PS1=\"[localhost-->${1}] \${PS1}\";" \
+                        "alias rsync=\"rsync -e 'ssh -p ${LOCAL_PORT}'\";" \
+                        "alias ssh=\"ssh" \
+                        "-o GlobalKnownHostsFile=/dev/null" \
+                        "-o UserKnownHostsFile=/dev/null" \
+                        "-o StrictHostKeyChecking=no" \
+                        "-p ${LOCAL_PORT}\";" \
+                        "alias sshfs=\"sshfs -p ${LOCAL_PORT}\";" \
+                        "alias scp=\"scp -P ${LOCAL_PORT}\"" \
+                   ) || :
     export SHELLOPTS
-    
+
     echo "Dropped connection to \"${1}\""
 }
 
@@ -285,44 +287,44 @@ elif [[ ${#} -eq 1 ]] ; then
     # does this start with '-'?
     if [[ "${1:0:1}" == "-" ]] ; then
 
-	if [[ (${1} == "-h") || (${1} == "--help") ]] ; then
-	    usage
-	elif [[ (${1} == "-x") || (${1} == "--exit") ]] ; then
-	    do_drop_connection
-	else
-	    usage
-	fi
+        if [[ (${1} == "-h") || (${1} == "--help") ]] ; then
+            usage
+        elif [[ (${1} == "-x") || (${1} == "--exit") ]] ; then
+            do_drop_connection
+        else
+            usage
+        fi
 
     # does not start with '-'
     else
 
-	check_3d_party_setup
+        check_3d_party_setup
 
-	if check_if_connection_is_available ${1} ; then
-	    do_ssh ${1}
-	else
-	    echo "Connection \"${1}\" not found."
-	    list_available_connections
-	fi
-	
+        if check_if_connection_is_available ${1} ; then
+            do_ssh ${1}
+        else
+            echo "Connection \"${1}\" not found."
+            list_available_connections
+        fi
+
     fi
 
-# Two parameters.  
+# Two parameters.
 elif [[ ${#} -eq 2 ]] ; then
     # Only option is "-e <connection>"
     if [[ (${1} == "-e") || (${1} == "--env") ]] ; then
 
-	check_3d_party_setup
+        check_3d_party_setup
 
-	if check_if_connection_is_available ${2} ; then
-	    do_connection_environment ${2}
-	else
-	    echo "Connection \"${2}\" not found."
-	    list_available_connections
-	fi
-	
+        if check_if_connection_is_available ${2} ; then
+            do_connection_environment ${2}
+        else
+            echo "Connection \"${2}\" not found."
+            list_available_connections
+        fi
+
     else
-	usage
+        usage
     fi
 else
     usage
